### ISSUE TITLE
functions missing in 3Dshape tutorial

### ISSUE THREAD

**Issue by huihuiqu** [Coricos/TdaToolbox#4]
Hi there, thank you for the nice toolbox. I was trying to run the 3D shape. However, there are some missing functions, e.g, functionize, build_landscapes. Could you please fix it? Thank you!

**Comment by Coricos** [comment]
Hey :) Sorry for the delay, I just fixed it. The scripts have been updated but the tutorial wasn't. Nice catch! Hope this will be useful to you.
